package com.example.audit.model;
import com.example.audit.exception.InvalidAuditEventException;
import java.time.Instant; import java.util.*;
/** Immutable description of something an application wishes to audit. */
public final class AuditEvent {
 private final UUID id; private final String actor; private final String role; private final String action; private final String resource; private final String resourceId; private final String status; private final Instant timestamp; private final String description; private final Map<String,Object> metadata;
 private AuditEvent(Builder b){id=b.id==null?UUID.randomUUID():b.id;actor=require(b.actor,"actor");action=require(b.action,"action");resource=require(b.resource,"resource");status=require(b.status,"status");timestamp=b.timestamp==null?Instant.now():b.timestamp;role=b.role;resourceId=b.resourceId;description=b.description;metadata=Collections.unmodifiableMap(new LinkedHashMap<>(b.metadata));}
 private static String require(String value,String field){if(value==null||value.isBlank())throw new InvalidAuditEventException(field+" must not be blank");return value;}
 public UUID getId(){return id;} public String getActor(){return actor;} public String getRole(){return role;} public String getAction(){return action;} public String getResource(){return resource;} public String getResourceId(){return resourceId;} public String getStatus(){return status;} public Instant getTimestamp(){return timestamp;} public String getDescription(){return description;} public Map<String,Object> getMetadata(){return metadata;}
 public static Builder builder(){return new Builder();}
 public static final class Builder {private UUID id;private String actor;private String role;private String action;private String resource;private String resourceId;private String status;private Instant timestamp;private String description;private final Map<String,Object> metadata=new LinkedHashMap<>();public Builder id(UUID v){id=v;return this;}public Builder actor(String v){actor=v;return this;}public Builder role(String v){role=v;return this;}public Builder action(String v){action=v;return this;}public Builder resource(String v){resource=v;return this;}public Builder resourceId(String v){resourceId=v;return this;}public Builder status(String v){status=v;return this;}public Builder status(AuditStatus v){status=Objects.requireNonNull(v,"status").name();return this;}public Builder timestamp(Instant v){timestamp=v;return this;}public Builder description(String v){description=v;return this;}public Builder metadata(Map<String,?> v){Objects.requireNonNull(v,"metadata").forEach(this::metadata);return this;}public Builder metadata(String key,Object value){if(key==null||key.isBlank())throw new InvalidAuditEventException("metadata key must not be blank");metadata.put(key,Objects.requireNonNull(value,"metadata value must not be null"));return this;}public AuditEvent build(){return new AuditEvent(this);}}
}
